# Example supers application config file

app_name = "My Test Application"

[[programs]]
name = "sleep"
cmd = "/bin/sleep"
args = ["3"]
env = {}
restartpolicy = "Always"

[[programs]]
name = "ls"
cmd = "ls"
args = ["-l"]
env = {}
restartpolicy = "OnError"